---

- name: Add http port to firewall open ports
  firewalld: service=http zone=public permanent=true state=enabled
- name: Add https to firewall open ports
  firewalld: service=https zone=public permanent=true state=enabled



- name: Create directory to store NGINX configuration
  file: path=/var/nginx/conf/conf.d state=directory owner=root group=root

- name: Copy default configuration files
  copy: src={{ item }} dest=/var/nginx/conf/{{ item }}
  with_items:
    - fastcgi_params
    - koi-utf
    - koi-win
    - mime.types
    - nginx.conf
    - scgi_params
    - uwsgi_params
    - win-utf

- copy: src=default.conf dest=/var/nginx/conf/conf.d/

- name: Create directory to store NGINX ssl keys
  file: path=/var/nginx/conf/ssl state=directory owner=root group=root

- name: Create directory to store NGINX enabled sites
  file: path=/var/nginx/conf/sites-enabled state=directory owner=root group=root

- name: create self-signed SSL cert
  command: openssl req -nodes -newkey rsa:2048 -x509 -subj "/CN=www.the-captains-shack.com" -days 3650
           -keyout /var/nginx/conf/ssl/www.the-captains-shack.com.key -out /var/nginx/conf/ssl/www.the-captains-shack.com.crt
           -extensions v3_ca
           creates=/var/nginx/conf/ssl/www.the-captains-shack.com.crt

- name: Create directory to store static web server pages
  file: path=/var/www state=directory

- name: Copy default start page
  copy: src={{ item }} dest=/var/www/{{ item }}
  with_items:
    - index.html
    - 404.css
    - 404.html
    - 500.html
    - 501.html
    - 502.html
    - 503.html
    - 504.html
    - 404.jpg
    - lew_kilborn_shack.jpg



#- name: Start NGINX Docker container
#  docker:
#    name: nginx
#    image: nginx:latest
#    state: reloaded
#    ports: 80:80, 443:443
#    volumes:
#    - /var/www:/usr/share/nginx/html:ro
#    - /var/nginx/conf:/etc/nginx:ro