---

- name: Add http port to firewall open ports
  firewalld: service=http zone=public permanent=true state=enabled
- name: Add https to firewall open ports
  firewalld: service=https zone=public permanent=true state=enabled



- name: Create directory to store NGINX configuration
  file: path=/var/nginx/conf/conf.d state=directory owner=root group=root

- name: Copy default configuration files
  copy: src={{ item }} dest=/var/nginx/conf/{{ item }}
  with_items:
    - fastcgi_params
    - koi-utf
    - koi-win
    - mime.types
    - nginx.conf
    - scgi_params
    - uwsgi_params
    - win-utf

- copy: src=default.conf dest=/var/nginx/conf/conf.d/

- name: Create directory to store NGINX ssl keys
  file: path=/var/nginx/conf/ssl state=directory owner=root group=root

- name: Create directory to store ssl keys for www.the-captains-shack.com
  file: path=/var/nginx/conf/ssl/www.the-captains-shack.com state=directory owner=root group=root

- name: Create directory to store NGINX enabled sites
  file: path=/var/nginx/conf/sites-enabled state=directory owner=root group=root

- name: create self-signed SSL cert
  command: openssl req -nodes -newkey rsa:2048 -x509 -subj "/CN=www.the-captains-shack.com" -days 3650
           -keyout /var/nginx/conf/ssl/www.the-captains-shack.com/privkey.pem
           -out /var/nginx/conf/ssl/www.the-captains-shack.com/cert.crt
           -extensions v3_ca
           creates=/var/nginx/conf/ssl/www.the-captains-shack.com/cert.crt

- name: copy the generated certificate as fullchain.pem
  command: cp /var/nginx/conf/ssl/www.the-captains-shack.com/cert.crt /var/nginx/conf/ssl/www.the-captains-shack.com/fullchain.pem
           creates="/var/nginx/conf/ssl/www.the-captains-shack.com/fullchain.pem"

- name: Create directory to store static web server pages
  file: path=/var/www state=directory

- name: Copy default start page
  copy: src={{ item }} dest=/var/www/{{ item }}
  with_items:
    - index.html
    - 404.css
    - 404.html
    - 500.html
    - 501.html
    - 502.html
    - 503.html
    - 504.html
    - 404.jpg
    - lew_kilborn_shack.jpg

- name: Copy Favicon related images
  copy: src=favicons/{{ item }} dest=/var/www/{{ item }}
  with_items:
    - android-chrome-36x36.png
    - android-chrome-48x48.png
    - android-chrome-72x72.png
    - android-chrome-96x96.png
    - apple-touch-icon-57x57.png
    - apple-touch-icon-60x60.png
    - apple-touch-icon-72x72.png
    - apple-touch-icon-76x76.png
    - apple-touch-icon-precomposed.png
    - apple-touch-icon.png
    - browserconfig.xml
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon-96x96.png
    - favicon.ico
    - manifest.json
    - mstile-150x150.png
    - mstile-310x150.png
    - mstile-70x70.png
    - safari-pinned-tab.svg

#- name: Start NGINX Docker container
#  docker:
#    name: nginx
#    image: nginx:latest
#    state: reloaded
#    ports: 80:80, 443:443
#    volumes:
#    - /var/www:/usr/share/nginx/html:ro
#    - /var/nginx/conf:/etc/nginx:ro