---
# installs the EPEL repository (Extra Packages for Enterprise Linux) for RHEL/CentOS.

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present