---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# installs the EPEL repository (Extra Packages for Enterprise Linux)
- include: epel.yml
  when: ansible_os_family == 'RedHat'

# Fail2Ban
- include: fail2ban-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: fail2ban-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes

# SSH
- include: ssh.yml

# Autoupdate of security patches
- include: autoupdate-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_autoupdate_enabled

- include: autoupdate-Debian.yml
  when: ansible_os_family == 'Debian' and security_autoupdate_enabled
