- hosts: all
  sudo: yes

  vars:
    dockerUsers:
      - jmm
      - dadou

  tasks:
  - name: configure docker yum repository
    copy: src=docker.repo
          dest=/etc/yum.repos.d/
          owner=root group=root mode=0644

  - name: install docker
    yum: name=docker-selinux
         state=present

  - name: start docker daemon
    service: name=docker
             state=started
             enabled=yes

  - name: create a docker user group
    group: name=docker
           state=present

  - name: add listed users to the docker group
    user: name="{{ item }}"
          groups=docker
          append=yes
    with_items: dockerUsers