---
- hosts: all
  sudo: yes
  vars_files:
    - vars/main.yml

  roles:
     - geerlingguy.repo-epel
     - geerlingguy.security

  tasks:
#  - name: change the SSH port
#    include: playbooks/remapSshPort.yml

#  - name: create users
#    include: playbooks/createUsers.yml
#
  - name: Install or update firewalld
    yum: pkg=firewalld state=latest

#  - name: Add open new deported ssh port
#    firewalld: port=10022/tcp zone=public permanent=true state=enabled
#
#  - name: Reload firewall rules
#    shell: firewall-cmd --reload

  - name: ensure ntpd is at the latest version
    yum: pkg=ntp state=latest
    notify:
    - restart ntpd

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted