---
- hosts: all
  sudo: yes

  tasks:
  - name: Install or update firewalld
    yum: pkg=firewalld state=latest

  - name: Add open new deported ssh port 
    firewalld: port=10022/tcp zone=public permanent=true state=enabled

  - name: Reload firewall rules
    shell: firewall-cmd --reload

  - name: ensure ntpd is at the latest version
    yum: pkg=ntp state=latest
    notify:
    - restart ntpd

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted