---
- hosts: all
  sudo: yes

  tasks:
  - name: Add open http port
    firewalld: service=http zone=public permanent=true state=enabled
  - name: Add open https port
    firewalld: service=https zone=public permanent=true state=enabled

  - name: Create directory to store NGINX configuration
    file: path=/var/nginx/conf state=directory

  - name: Create directory to store static web server pages
    file: path=/var/www state=directory

  - name: Start NGINX Docker container
    docker:
      name: nginx
      image: nginx:latest
      state: reloaded
      ports: 80:80, 443:443
      volumes:
      - /var/www:/usr/share/nginx/html:ro

#      - /var/nginx/conf:/etc/nginx:ro