---

- name: Add gogs special ssh port to firewall open ports
  firewalld: port=10022/tcp zone=public permanent=true state=enabled

#- name: Add gogs http port to firewall open ports
#  firewalld: port=10080/tcp zone=public permanent=true state=enabled

- name: Create directory to store GOGS data and configuration
  file: path={{ work_dir }}/gogs state=directory  owner=root group=root

- name: Create directory to store ssl keys for git.the-captains-shack.com
  file: path={{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com state=directory owner=root group=root

#/var/gogs/gogs/conf
- name: create self-signed SSL cert
  command: openssl req -nodes -newkey rsa:2048 -x509 -subj "/CN=git.the-captains-shack.com" -days 3650
           -keyout {{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/privkey.pem
           -out {{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/cert.crt
           -extensions v3_ca
           creates={{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/cert.crt

- name: copy the generated certificate as fullchain.pem
  command: cp {{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/cert.crt {{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/fullchain.pem
           creates="{{ work_dir }}/nginx/conf/ssl/git.the-captains-shack.com/fullchain.pem"

- name: copy the nginx proxy configuration
  copy: src=gogs_proxy.conf dest={{ work_dir }}/nginx/conf/sites-enabled/

- name: Update main docker-file
  blockinfile:
    destfile: "{{ work_dir }}/docker/docker-compose.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (GOGS)"
    insertafter: "services:"
    block: |
      dummy_line
        gogs:
          image: gogs/gogs:latest
          ports:
            - "10022:22"
            - "10080:3000"
          volumes:
            - {{ work_dir }}/gogs:/data
          restart: unless-stopped

- name: Removed a temporary dummy line (workaround for issue #8)
  lineinfile:
    dest: "{{ work_dir }}/docker/docker-compose.yml"
    regexp: ^dummy_line$
    state: absent
  changed_when: false


