---

- name: Create directory to the backup related files
  file: path={{ work_dir }}/backup/docker-s3cmd/files state=directory owner=root group=root

- name: Copy default configuration files
  copy: src={{ item }} dest={{ work_dir }}/backup/{{ item }}
  with_items:
    - backup.env
    - docker-s3cmd/Dockerfile
    - docker-s3cmd/files/main.sh
    - docker-s3cmd/files/s3cfg

- name: Update Compose template and copy
  template: src=docker-compose.j2
            dest={{ work_dir }}/backup/docker-compose.yml
            force=yes

- name: Update restore command template and copy
  template: src=restore.j2
            dest={{ work_dir }}/backup/restore.sh
            mode="a+rx"
            force=yes

- name: Load keys
  include_vars: "S3backup_keys.yml"

- name: Copy S3backup keys
  copy:
    content: "{{ key_data }}"
    dest: "{{ work_dir }}/backup/S3backup_keys.env"

