---

- name: Create directory to the backup related files
  file: path=/var/backup/docker-s3cmd/files state=directory owner=root group=root

- name: Copy default configuration files
  copy: src={{ item }} dest=/var/backup/{{ item }}
  with_items:
    - backup.env
    - docker-compose.yml
    - restore.sh
    - docker-s3cmd/Dockerfile
    - docker-s3cmd/files/main.sh
    - docker-s3cmd/files/s3cfg

- name: make backup.sh executable
  file: path=/var/backup/restore.sh
        mode="a+rx"

- name: Load keys
  include_vars: "S3backup_keys.yml"

- name: Copy S3backup keys
  copy:
    content: "{{ key_data }}"
    dest: /var/backup/S3backup_keys.env

