web:
  image: nginx:latest
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - /data/www:/usr/share/nginx/html:ro
   - /data/nginx/conf:/etc/nginx:ro
  links:
   - gogs

gogs:
    image: gogs/gogs:latest
    ports:
     - "10022:22"
     - "10080:3000"
    volumes:
    - /data/gogs:/data