---

- name: Create directory to HUGO Dockerfile
  file: path={{ work_dir }}/docker/hugo-dockerfile state=directory  owner=root group=root

- name: Copy the Dockerfile related data
  copy: src={{ item }} dest={{ work_dir }}/docker/hugo-dockerfile/{{ item }}
  with_items:
    - Dockerfile
    - run.sh

- name: set run.sh as executable
  file: path={{ work_dir }}/docker/hugo-dockerfile/run.sh state=touch mode="u+rx,g+rx,o+rx"

- name: Update main docker-file
  blockinfile:
    destfile: "{{ work_dir }}/docker/docker-compose.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (Hugo)"
    insertafter: "services:"
    block: |
      dummy_line
        hugo:
          build: ./hugo-dockerfile
          volumes:
            - hugo_src:/src
            - hugo_out:/output
          environment:
            #- HUGO_WATCH=true
            - HUGO_REFRESH_TIME=3600
            - HUGO_THEME=casper
            - HUGO_BASEURL=https://www.the-captains-shack.com
          restart: unless-stopped

- name: Removed a temporary dummy line (workaround for issue #8)
  lineinfile:
    dest: "{{ work_dir }}/docker/docker-compose.yml"
    regexp: ^dummy_line$
    state: absent
  changed_when: false