---

- name: Create directory to HUGO Dockerfile
  file: path={{ work_dir }}/docker/hugo-dockerfile state=directory  owner=root group=root

- name: Copy the Dockerfile related data
  copy: src={{ item }} dest={{ work_dir }}/docker/hugo-dockerfile/{{ item }}
  with_items:
    - Dockerfile
    - run.sh

- name: set run.sh as executable
  file: path={{ work_dir }}/docker/hugo-dockerfile/run.sh state=touch mode="u+rx,g+rx,o+rx"


