- name: Include OS-specific variables.
  include_vars: "docker_vars.yml"

- name: install docker SElinux policies (requiered for Centos)
  yum: name=docker-selinux
       state=absent

- name: Update the complete system
  yum: name=*
       state=latest

- name: Install python setup tools
  yum: name=python-setuptools

- name: configure docker yum repository
  copy: src=docker.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: install docker
  yum: name={{ docker_engine_version }}*
       state=present

- name: start docker daemon
  service: name=docker
           state=started
           enabled=yes

- name: create a docker user group
  group: name=docker
         state=present

- name: add listed users to the docker group
  user: name="{{ item }}"
        groups=docker
        append=yes
  with_items: "{{dockerUsers}}"

#FIXME: make this version configurable
- name: Download the script to run docler-compose from a container
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64"
    dest: /usr/bin/docker-compose
    group: root
    owner: root
    mode: "0755"
    

- name: Directory to store the docker-compose config
  file: path={{ work_dir }}/docker state=directory owner=root group=root

- name: Update restart_web bash and copy
  template: src=restart_web.j2
            dest={{ work_dir }}/docker/restart_web.sh
            mode="a+rx"
            force=yes
