#tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: create admin accounts
    user: name="{{ item }}"
        createhome=yes
        generate_ssh_key=no
        state=present
        groups=wheel
        password="$6$rounds=100000$DotqIzX010bHLjJL$Q0UtYwxBQkCWtYZsx6XKUYKOTIE3jbjMkMrIQf2IXbmsBFpnyUyorsdCTZpRl4uRUWG6D6VJo5BKLxgpJA3GV."
    with_items: "{{adminUsers}}"

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'


  - name : update authorized keys
    authorized_key: user="{{ item }}"
                    key="{{ lookup('file', 'public_keys/' + item) }}"
                    state=present
                    manage_dir=yes
                    exclusive=yes
    with_items: "{{adminUsers}}"

# To generate password :python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
